/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUnicrowClaim, IUnicrowClaimInterface } from "../IUnicrowClaim";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "escrows",
        type: "uint256[]",
      },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "escrowId",
        type: "uint256",
      },
    ],
    name: "singleClaim",
    outputs: [
      {
        internalType: "uint256[5]",
        name: "",
        type: "uint256[5]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "crowRewards_",
        type: "address",
      },
    ],
    name: "updateCrowRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "protocolFeeAddress_",
        type: "address",
      },
    ],
    name: "updateProtocolFeeAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "crowRewards_",
        type: "address",
      },
    ],
    name: "updateStakingRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IUnicrowClaim__factory {
  static readonly abi = _abi;
  static createInterface(): IUnicrowClaimInterface {
    return new utils.Interface(_abi) as IUnicrowClaimInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUnicrowClaim {
    return new Contract(address, _abi, signerOrProvider) as IUnicrowClaim;
  }
}
